version: "3.3"
services:
  master:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/apps
       - ./data:/opt/data
    environment:
      - SPARK_LOCAL_IP=master
      - SPARK_WORKLOAD=master
  worker-a:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9091:8080"
      - "7003:7000"
    depends_on:
      - master
    environment:
      - SPARK_MASTER=spark://master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=worker-a
    volumes:
       - ./apps:/opt/apps
       - ./data:/opt/data
  worker-b:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9092:8080"
      - "7004:7000"
    depends_on:
      - master
    environment:
      - SPARK_MASTER=spark://master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=worker-b
    volumes:
        - ./apps:/opt/apps
        - ./data:/opt/data
  demo-database:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=casa1234

